"""fix models fields to work with postgres

Revision ID: 9968749bc3fb
Revises: 8ed846c4eb1e
Create Date: 2026-05-18 16:02:01.550883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from fastapi_app.src.core.config import settings

# revision identifiers, used by Alembic.
revision: str = '9968749bc3fb'
down_revision: Union[str, Sequence[str], None] = '8ed846c4eb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_post', 'pub_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False,
               schema='application')
    op.alter_column('blog_post', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False,
               schema='application')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_post', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='application')
    op.alter_column('blog_post', 'pub_date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='application')
    # ### end Alembic commands ###
