"""add_post_and_comment_images

Revision ID: ebd6c7dae746
Revises: 9968749bc3fb
Create Date: 2026-05-18 17:15:08.858489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from fastapi_app.src.core.config import settings

# revision identifiers, used by Alembic.
revision: str = 'ebd6c7dae746'
down_revision: Union[str, Sequence[str], None] = '9968749bc3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['application.blog_post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='application'
    )
    op.create_table('comment_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['application.blog_comment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='application'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_images', schema='application')
    op.drop_table('post_images', schema='application')
    # ### end Alembic commands ###
