"""Test: add image2_field in blog_post

Revision ID: 9297f81bc886
Revises: 7ebb4fb28988
Create Date: 2026-03-18 21:14:37.203679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9297f81bc886'
down_revision: Union[str, Sequence[str], None] = '7ebb4fb28988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('image2', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'image2')
    # ### end Alembic commands ###
