"""Test delete changes

Revision ID: 4bbd7b30668d
Revises: 9297f81bc886
Create Date: 2026-03-18 21:16:04.658976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bbd7b30668d'
down_revision: Union[str, Sequence[str], None] = '9297f81bc886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'image2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('image2', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
