"""add new field - update table

Revision ID: 70bfc5f8aebc
Revises: 4bbd7b30668d
Create Date: 2026-03-20 13:06:10.650767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70bfc5f8aebc'
down_revision: Union[str, Sequence[str], None] = '4bbd7b30668d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('image2', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'image2')
    # ### end Alembic commands ###
